'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace FVK

    Partial Public Class BookmarkButton

        '''<summary>
        '''bookmarkSpan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bookmarkSpan As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''BookmarkButtonUpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BookmarkButtonUpdatePanel As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''BookmarkAddedButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BookmarkAddedButton As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
