'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace FVK

    Partial Public Class SelectFriends

        '''<summary>
        '''selectfriendsdiv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents selectfriendsdiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''scriptSpan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents scriptSpan As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''SelectFriendsUpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SelectFriendsUpdatePanel As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''TempList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TempList As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''InitButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents InitButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''FriendsRepeater control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FriendsRepeater As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace
