'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace FVK

    Partial Public Class SendUserStatus

        '''<summary>
        '''Div1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''SendUserStatusUpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SendUserStatusUpdatePanel As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''SendStatusText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SendStatusText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ButtonSpan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonSpan As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''StatusSentButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StatusSentButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''SendErrorButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SendErrorButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''permissions1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents permissions1 As Global.FVK.Permissions
    End Class
End Namespace
