'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace FVK

    Partial Public Class StreamPublishFriendList

        '''<summary>
        '''StreamPublishFriendListUpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StreamPublishFriendListUpdatePanel As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''titleLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents titleLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''BoxTextLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BoxTextLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''streampublishpopup1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents streampublishpopup1 As Global.FVK.StreamPublishPopup

        '''<summary>
        '''HideButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HideButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''SelectedImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SelectedImage As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''RadioItemsSpan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadioItemsSpan As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    End Class
End Namespace
