'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace FVK

    Partial Public Class StreamPublishPopup

        '''<summary>
        '''StreamPublishUpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StreamPublishUpdatePanel As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''NameHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NameHiddenField As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HrefHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HrefHiddenField As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''CaptionHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CaptionHiddenField As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''DescriptionHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DescriptionHiddenField As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''MessagePromptHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MessagePromptHiddenField As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''UserMessageHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserMessageHiddenField As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''ActionLinksHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ActionLinksHiddenField As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''TargetIdHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TargetIdHiddenField As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''ActorIdHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ActorIdHiddenField As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''MediaHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MediaHiddenField As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''PropertiesHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PropertiesHiddenField As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''ReturnedPostIdHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReturnedPostIdHiddenField As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''PublishButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PublishButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''streamPublishSpan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents streamPublishSpan As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ConfirmedSendButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ConfirmedSendButton As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
