'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace FVK_Demo

    Partial Public Class BookmarkButton

        '''<summary>
        '''bookmark1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents bookmark1 As Global.FVK.BookmarkButton

        '''<summary>
        '''BookmarkLabelUpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BookmarkLabelUpdatePanel As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''BookmarkedLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BookmarkedLabel As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
