'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace FVK_Demo

    Partial Public Class DataAccess

        '''<summary>
        '''UserIdLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserIdLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UserNameLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserNameLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UserEmailLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserEmailLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''FriendsLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FriendsLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ErrorLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ErrorLabel As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
