'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5420
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace FVK_Demo

    Partial Public Class SelectFriends

        '''<summary>
        '''selectfriends1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents selectfriends1 As Global.FVK.SelectFriends

        '''<summary>
        '''SelectedFriendsLabelUpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SelectedFriendsLabelUpdatePanel As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''SelectedFriendsLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SelectedFriendsLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''FiltersUpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FiltersUpdatePanel As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''FilterTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FilterTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''FilterIfStartsWithButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FilterIfStartsWithButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''FilterIfContainsButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FilterIfContainsButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''SelectorsUpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SelectorsUpdatePanel As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''SelectAllButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SelectAllButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''UnselectAllButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UnselectAllButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ErrorLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ErrorLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''loginbutton1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents loginbutton1 As Global.FVK.LoginButton
    End Class
End Namespace
